// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultipleDBSource.Data;

#nullable disable

namespace MultipleDBSource.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultipleDBSource.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedTimestamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("MultipleDBSource.Models.Person", b =>
                {
                    b.OwnsOne("MultipleDBSource.Models.AuditTrail", "History", b1 =>
                        {
                            b1.Property<Guid>("PersonId");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasJsonPropertyName("createdBy");

                            b1.Property<DateTime>("ModifiedAt")
                                .HasJsonPropertyName("modifiedAt");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1
                                .ToJson("History")
                                .HasColumnType("json");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("MultipleDBSource.Models.MoreInfo", "Details", b1 =>
                        {
                            b1.Property<Guid>("PersonId");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasJsonPropertyName("address");

                            b1.Property<string>("Email")
                                .HasJsonPropertyName("email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasJsonPropertyName("firstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasJsonPropertyName("lastName");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1
                                .ToJson("Details")
                                .HasColumnType("json");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");

                            b1.OwnsMany("MultipleDBSource.Models.EmergencyContact", "Contacts", b2 =>
                                {
                                    b2.Property<Guid>("MoreInfoPersonId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasJsonPropertyName("name");

                                    b2.Property<string>("Phone")
                                        .IsRequired()
                                        .HasJsonPropertyName("phone");

                                    b2.Property<string>("Relationship")
                                        .IsRequired()
                                        .HasJsonPropertyName("relationship");

                                    b2.HasKey("MoreInfoPersonId", "__synthesizedOrdinal");

                                    b2.ToTable("Persons");

                                    b2.WithOwner()
                                        .HasForeignKey("MoreInfoPersonId");
                                });

                            b1.OwnsOne("MultipleDBSource.Models.Preferences", "UserPrefs", b2 =>
                                {
                                    b2.Property<Guid>("MoreInfoPersonId");

                                    b2.Property<bool>("Notifications")
                                        .HasJsonPropertyName("notifications");

                                    b2.Property<string>("Theme")
                                        .IsRequired()
                                        .HasJsonPropertyName("theme");

                                    b2.HasKey("MoreInfoPersonId");

                                    b2.ToTable("Persons");

                                    b2.WithOwner()
                                        .HasForeignKey("MoreInfoPersonId");
                                });

                            b1.Navigation("Contacts");

                            b1.Navigation("UserPrefs");
                        });

                    b.Navigation("Details");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
